DROP TABLE if exists book;
DROP TABLE if exists author;

create table book (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    isbn varchar(255),
    publisher varchar(255),
    title varchar(255),
    author_id BIGINT,
    primary key (id)
);

create table author (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name varchar(255),
    last_name varchar(255),
    primary key (id)
);
